config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get 'teacher', to: 'teacher#index'
  get 'vildanov', to: 'vildanov#index'
  get 'cathedra', to: 'cathedra#index'
  get 'davletshin', to: 'davletshin#index'
  get 'students', to: 'students#index'
  get '/allpub', to: 'allpub#index'
  get '/nirs', to: 'nirs#index'
  get 'nirs/new', to: 'nirs#new', as: 'new_nir' # убедитесь, что этот маршрут настроен
  get 'studpub', to: 'studpub#index'
  post '/cathedra/select', to: 'cathedra#select_cathedra', as: 'cathedra_select'
  resources :cathedra, only: [:index, :edit, :update, :destroy]
  resources :nirs, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :authors, only: [:new, :create]
  resources :vildanov, only: [:index]
  resources :studpub, only: [:index]
  resources :cathedra, only: [:index] do
    member do
      get 'edit'
      patch 'update'
      delete 'destroy'
    end
  end
end

app/controllers/teacher_controller.rb
require 'csv'

class TeacherController < ApplicationController
  def index
    @teachers_publications = Author
                             .joins(nir_authors: :nir)
                             .where(status: 'преподаватель')
                             .select('authors.lastname', 'authors.name', 'authors.fathername', 'nirs.title', 'nirs.dtr', 'nirs.doi', 'nirs.href', 'nirs.output')

    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(@teachers_publications), filename: "teachers_publications_#{Time.zone.now.to_date}.csv" }
    end
  end

  private

  def generate_csv(data)
    CSV.generate(headers: true) do |csv|
      csv << ['Фамилия', 'Имя', 'Отчество', 'Название НИР', 'Дата публикации', 'DOI', 'Ссылка на пуликацию', 'Результат публикации']

      data.each do |publication|
        csv << [
          publication.lastname,
          publication.name,
          publication.fathername,
          publication.title,
          publication.dtr,
          publication.doi,
          publication.href,
          publication.output
        ]
      end
    end
  end
end

app/views/teacher/index.html.erb
<div class="table-responsive">
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th colspan="3">ФИО</th>
        <th scope="col">Название НИР</th>
        <th scope="col">Дата публикации</th>
        <th scope="col">DOI</th>
        <th scope="col">Ссылка на публикацию</th>
        <th scope="col">Публикация</th>
      </tr>
    </thead>     
    <tbody>
      <% @teachers_publications.each do |row| %>
        <tr>
          <td colspan="3"><%= "#{row.lastname}<br> #{row.name}<br> #{row.fathername}".html_safe %></td>
          <td><%= row.title %></td>
          <td><%= row.dtr %></td>
          <td><%= row.doi %></td>
          <td style="word-wrap: break-word; max-width: 200px;"><%= link_to row.href, row.href, class: "wrap-link" %></td>
          <td><%= row.output %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'Скачать CSV', teacher_path(format: 'csv'), class: "btn btn-primary" %>