config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get 'teacher', to: 'teacher#index'
  get 'vildanov', to: 'vildanov#index'
  get 'cathedra', to: 'cathedra#index'
  get 'davletshin', to: 'davletshin#index'
  get 'students', to: 'students#index'
  get '/allpub', to: 'allpub#index'
  get '/nirs', to: 'nirs#index'
  get 'nirs/new', to: 'nirs#new', as: 'new_nir' # убедитесь, что этот маршрут настроен
  get 'studpub', to: 'studpub#index'
  post '/cathedra/select', to: 'cathedra#select_cathedra', as: 'cathedra_select'
  resources :cathedra, only: [:index, :edit, :update, :destroy]
  resources :nirs, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :authors, only: [:new, :create]
  resources :vildanov, only: [:index]
  resources :studpub, only: [:index]
  resources :cathedra, only: [:index] do
    member do
      get 'edit'
      patch 'update'
      delete 'destroy'
    end
  end
end

app/models/nir.rb
class Nir < ApplicationRecord
  self.table_name = 'nirs'
  self.primary_key = 'nir_id'
  belongs_to :cathedra, optional: true
  has_many :nir_authors, foreign_key: 'nir_id'
  has_many :authors, through: :nir_authors
  validates :title, presence: true, length: { maximum: 320 }
  validates :dtr, presence: true
  validates :nirtype, presence: true, inclusion: { in: %w(article thesis monograph patent program database book) }
  validates :volume, presence: true, numericality: true
  validates :doi, presence: true, length: { maximum: 256 }
  validates :core_rinz, inclusion: { in: [0, 1] }
  validates :rinz, inclusion: { in: [0, 1] }
  validates :scopus, inclusion: { in: [0, 1] }
  validates :webofscience, inclusion: { in: [0, 1] }
  validates :vak, inclusion: { in: [0, 1] }
  validates :id_adviser, inclusion: { in: [0, 1] }
  validates :href, presence: true, length: { maximum: 600 }
  validates :output, presence: true
  accepts_nested_attributes_for :nir_authors, allow_destroy: true
  accepts_nested_attributes_for :authors
end

app/controllers/nir_controller.rb
class NirController < ApplicationController
    def index
    end
    TYPES = [
        'article',
        'thesis',
        'monograph',
        'patent',
        'program',
        'database',
        'book'
      ].freeze
end

app/controllers/nirs_controller.rb
class NirsController < ApplicationController
  def index
    @nirs = Nir.all
  end

  def new
    @nir = Nir.new
    @students = Author.where(status: 'студент')
    @advisers = Author.where(status: 'преподаватель')
  end

  def destroy
    @nir = Nir.find(params[:id])
    @nir.nir_authors.destroy_all # Удаление всех связанных записей из таблицы nir_authors
    @nir.destroy # Удаление записи из таблицы nirs
    redirect_to nirs_path, notice: 'Научная публикация успешно удалена'
  end

  def edit
    logger.debug "params[:id]: #{params[:id]}" # Debug line to print the id
    @nir = Nir.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to nirs_path, alert: "Научная публикация не найдена"
  end

  def create
    @nir = Nir.new(nir_params.except(:author_ids, :percent))
    if @nir.save
      params[:author_ids]&.each_with_index do |author_id, i|
        next unless author_id.present? && params[:percent][i].present?
        nir_author = NirAuthor.new(nir_id: @nir.id, author_id: author_id, percent: params[:percent][i])
        nir_author.save
      end
      redirect_to new_nir_path, notice: 'Научная публикация успешно добавлена'
    else
      @students = Author.where(status: 'студент')
      @advisers = Author.where(status: 'преподаватель')
      render :new
    end
  end

  def update
    @nir = Nir.find(params[:id])
    if @nir.update(nir_params)
      redirect_to nirs_path, notice: 'Научная публикация успешно обновлена'
    else
      render :edit
    end
  end

  private

  def nir_params
    params.require(:nir).permit(:title, :dtr, :nirtype, :volume, :doi, :core_rinz, :rinz, :scopus, :webofscience, :vak, :id_adviser, :href, :output, author_ids: [], percent: [])
  end
end

app/views/nirs/edit.html.erb
<!-- app/views/nirs/edit.html.erb -->
<div class="container">
  <h1>Редактировать НИР</h1>
  <%= form_for(@nir) do |f| %>
    <div class="form-group">
      <%= f.label :title, 'Название НИР' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :dtr, 'Дата' %>
      <%= f.date_field :dtr, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :nirtype, 'Тип' %>
      <%= f.text_field :nirtype, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :volume, 'Объем' %>
      <%= f.number_field :volume, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :doi, 'DOI' %>
      <%= f.text_field :doi, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :href, 'Ссылка' %>
      <%= f.text_field :href, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :output, 'Выходные данные' %>
      <%= f.text_area :output, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/nirs/index.html.erb
<div class="table-responsive">
  <table class="table table-bordered table-sm">
    <thead class="thead-dark">
      <tr>
        <th colspan="3" style="width: 150px; word-wrap: break-word;">ФИО</th>
        <th scope="col" style="width: 200px; word-wrap: break-word;">Название НИР</th>
        <th scope="col" style="width: 100px; word-wrap: break-word;">Дата публикации</th>
        <th scope="col" style="width: 100px; word-wrap: break-word;">DOI</th>
        <th scope="col" style="width: 200px; word-wrap: break-word;">Ссылка на публикацию</th>
        <th scope="col" style="width: 300px; word-wrap: break-word;">Публикация</th>
        <th scope="col" style="width: 150px; word-wrap: break-word;">Действия</th>
      </tr>
    </thead>     
    <tbody>
      <% @nirs.each do |publication| %>
        <% publication.nir_authors.each do |nir_author| %>
          <% author = nir_author.author %>
          <tr>
            <td colspan="3" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;"><%= "#{author.lastname}<br> #{author.name}<br> #{author.fathername}".html_safe %></td>
            <td class="title-cell" style="width: 200px;"><%= publication.title %></td>
            <td style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;"><%= publication.dtr %></td>
            <td style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;"><%= publication.doi %></td>
            <td style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 200px;"><%= link_to publication.href, publication.href, class: "wrap-link" %></td>
            <td style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 300px;"><%= publication.output %></td>
            <td>
              <%= link_to 'Редактировать', edit_nir_path(publication.id), class: 'btn btn-primary btn-sm' %>
              <%= link_to 'Удалить', nir_path(publication), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/nirs/new.html.erb
<!-- app/views/nirs/new.html.erb -->
<div class="container">
  <h1 class="mt-4">Новая публикация</h1>

  <%= form_with(model: @nir, local: true, class: "mt-4") do |form| %>
    <% if @nir.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@nir.errors.count, "ошибка") %> не позволяет сохранить эту публикацию:</h2>
        <ul>
          <% @nir.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title, "Название" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :dtr, "Дата публикации" %>
      <%= form.date_select :dtr, { start_year: Date.today.year - 10, end_year: Date.today.year }, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :nirtype, "Тип НИР" %>
      <%= form.select :nirtype, options_for_select([['Статья', 'article'], ['Тезисы', 'thesis'], ['Монография', 'monograph'], ['Патент', 'patent'], ['Программа', 'program'], ['База данных', 'database'], ['Книга', 'book']]), {}, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :volume, "Объем" %>
      <%= form.number_field :volume, step: :any, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :doi, "DOI" %>
      <%= form.text_field :doi, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :core_rinz, "Core Rinz" %>
      <%= form.check_box :core_rinz, {}, 1, 0 %>
    </div>

    <div class="form-group">
      <%= form.label :rinz, "Rinz" %>
      <%= form.check_box :rinz, {}, 1, 0 %>
    </div>

    <div class="form-group">
      <%= form.label :scopus, "Scopus" %>
      <%= form.check_box :scopus, {}, 1, 0 %>
    </div>

    <div class="form-group">
      <%= form.label :webofscience, "Web of Science" %>
      <%= form.check_box :webofscience, {}, 1, 0 %>
    </div>

    <div class="form-group">
      <%= form.label :vak, "ВАК" %>
      <%= form.check_box :vak, {}, 1, 0 %>
    </div>

    <div class="form-group">
      <%= form.label :id_adviser, "Руководитель" %>
      <%= form.select :id_adviser, @advisers.map { |a| ["#{a.lastname} #{a.name} #{a.fathername}", a.author_id] }, { include_blank: true }, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :href, "Ссылка" %>
      <%= form.text_field :href, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :output, "Результат" %>
      <%= form.text_area :output, class: "form-control" %>
    </div>

    <h3>Авторы</h3>
    <% @students.each_with_index do |student, i| %>
      <div class="form-group">
        <%= check_box_tag "author_ids[]", student.author_id, false, id: "author_ids_#{i}", class: "form-check-input" %>
        <%= label_tag "author_ids_#{i}", "#{student.lastname} #{student.name} #{student.fathername}", class: "form-check-label" %>
        <%= text_field_tag "percent[]", '', placeholder: 'Процент', class: "form-control" %>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.submit "Создать", class: "btn btn-primary" %>
    </div>
  <% end %>

  <p>
    <%= link_to 'Добавить нового автора', new_author_path, class: "btn btn-secondary" %>
  </p>
</div>