config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get 'teacher', to: 'teacher#index'
  get 'vildanov', to: 'vildanov#index'
  get 'cathedra', to: 'cathedra#index'
  get 'davletshin', to: 'davletshin#index'
  get 'students', to: 'students#index'
  get '/allpub', to: 'allpub#index'
  get '/nirs', to: 'nirs#index'
  get 'nirs/new', to: 'nirs#new', as: 'new_nir' # убедитесь, что этот маршрут настроен
  get 'studpub', to: 'studpub#index'
  post '/cathedra/select', to: 'cathedra#select_cathedra', as: 'cathedra_select'
  resources :cathedra, only: [:index, :edit, :update, :destroy]
  resources :nirs, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :authors, only: [:new, :create]
  resources :vildanov, only: [:index]
  resources :studpub, only: [:index]
  resources :cathedra, only: [:index] do
    member do
      get 'edit'
      patch 'update'
      delete 'destroy'
    end
  end
end

app/controllers/davletshin_controller.rb
class DavletshinController < ApplicationController
    def index
        @students_publications = fetch_students_publications
        respond_to do |format|
          format.html
          format.csv { send_data generate_csv(@students_publications), filename: "students_publications.csv" }
        end
      end
    
      private
    
      def fetch_students_publications
        student_id = params[:student_id]
        Author
          .joins(nir_authors: :nir)
          .where(nir_authors: { author_id: student_id }, status: 'студент')
          .select('authors.lastname', 'authors.name', 'authors.fathername', 'nirs.title', 'nirs.dtr', 'nirs.doi', 'nirs.href', 'nirs.output')
      end
         
    
      def generate_csv(data)
        CSV.generate(headers: true) do |csv|
            csv << ['Фамилия', 'Имя', 'Отчество', 'Название НИР', 'Дата публикации', 'DOI', 'Ссылка на пуликацию', 'Результат публикации']
          data.each do |publication|
            csv << [
              publication.lastname,
              publication.name,
              publication.fathername,
              publication.title,
              publication.dtr,
              publication.doi,
              publication.href,
              publication.output
            ]
          end
        end
      end
    end

app/views/davletshin/index.html.erb
<%= form_with url: davletshin_path, method: :get, local: true do %>
  <div class="form-group mr-2">
    <%= select_tag :student_id, options_from_collection_for_select(Author.where(status: 'студент'), :author_id, :full_name), prompt: "Выберите студента" %><br>
  </div>
  <div class="actions">
    <%= submit_tag "Показать публикации", class: "btn btn-primary" %><br>
  </div>
<% end %>

<% if @students_publications.present? %>
  <h2>Publications for <%= @students_publications.first.name %> <%= @students_publications.first.lastname %></h2>
  <table>
    <thead>
      <tr>
        <th colspan="3">ФИО</th>
        <th scope="col">Название НИР</th>
        <th scope="col">Дата публикации</th>
        <th scope="col">DOI</th>
        <th scope="col">Ссылка на публикацию</th>
        <th scope="col">Публикация</th>
      </tr>
    </thead>
    <tbody>
      <% @students_publications.each do |publication| %>
        <tr>
          <td colspan="3"><%= "#{publication.lastname}<br> #{publication.name}<br> #{publication.fathername}".html_safe %></td>
          <td><%= publication.title %></td>
          <td><%= publication.dtr %></td>
          <td><%= publication.doi %></td>
          <td style="word-wrap: break-word; max-width: 200px;"><%= link_to publication.href, publication.href %></td>
          <td><%= publication.output %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Не найдено публикации для выбранного студента.</p>
<% end %>
<%= link_to 'Скачать CSV', davletshin_path(format: 'csv', student_id: params[:student_id]), class: 'btn btn-primary' %>